version: '3.9'

services:
  docmanager:
    image: ${DOCKER_REGISTRY-}docmanager
    build:
      context: .
      dockerfile: DocManager/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__Database=mongodb://admin:password@mongo"
      - "ClamAV__URL=clamav"
      - "ClamAV__Port=3310"
    depends_on:
      - mongo
      - clamav

  mongo:
    image: mongodb/mongodb-community-server:7.0-ubi8
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongoData:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongo
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_OPTIONS_EDITORTHEME=rubyblue
    ports:
      - "8005:8081"
    depends_on:
      - mongo

  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    ports:
      - "8006:3310"
    volumes:
      - clamavData:/var/lib/clamav

volumes:
  mongoData:
    name: mongoData
  clamavData:
    name: clamavData

